version: '3.1'

services:
  api:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3500:3500"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
